import http from "http";
import dotenv from "dotenv";

import { configExists, loadConfig } from "./src/config.js";
import { runSetupWizard } from "./src/setup.js";
import { saveReport } from "./src/reportStore.js";
import { startScheduler } from "./src/scheduler.js";

dotenv.config();

// ================= AI REPORT (NO API VERSION - STABLE) =================
async function generateAIReport(topic) {
  const dateLabel = new Date().toDateString();

  return `
Daily Report
Topic: ${topic}
Date: ${dateLabel}

Summary:
This report provides a structured analysis of ${topic} generated by the AI Agent system.

Key Insights:
- ${topic} is an important and active domain of study.
- Continuous developments are observed in this area.
- Data processing completed successfully by the agent pipeline.
- System generated this report using internal logic.

Observations:
- ${topic} shows ongoing relevance in modern trends.
- High potential for further exploration and development.
- Stable system behavior detected during execution.

Recommendations:
- Continue monitoring ${topic}.
- Collect additional structured data over time.
- Use automated reporting for continuous insights.

End of Report.
`;
}

// ================= SERVER =================
const server = http.createServer(async (req, res) => {

  // HOME PAGE (UI)
  if (req.url === "/" && req.method === "GET") {
    res.writeHead(200, { "Content-Type": "text/html" });

    res.end(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>AI Agent</title>
        <style>
          body { font-family: Arial; text-align:center; margin-top:50px; }
          input { padding:10px; width:250px; }
          button { padding:10px 15px; cursor:pointer; }
        </style>
      </head>
      <body>
        <h1>AI Agent 🚀</h1>

        <form method="GET" action="/generate">
          <input name="topic" placeholder="Enter topic..." required />
          <button type="submit">Generate Report</button>
        </form>

        <br><br>

        <a href="/status">Check Status</a>
      </body>
      </html>
    `);

    return;
  }

  // GENERATE REPORT
  if (req.url.startsWith("/generate")) {
    const url = new URL(req.url, `http://${req.headers.host}`);
    const topic = url.searchParams.get("topic") || "General Topic";

    const report = await generateAIReport(topic);

    saveReport(report);

    res.writeHead(200, { "Content-Type": "text/html" });

    res.end(`
      <html>
      <head>
        <title>Generated Report</title>
      </head>
      <body style="font-family:Arial; padding:20px;">
        <h2>Generated Report</h2>

        <pre style="background:#f4f4f4; padding:15px;">${report}</pre>

        <br>
        <a href="/">← Back</a>
      </body>
      </html>
    `);

    return;
  }

  // STATUS
  if (req.url === "/status") {
    res.writeHead(200, { "Content-Type": "application/json" });

    res.end(JSON.stringify({
      status: "active",
      service: "ai-agent",
      time: new Date().toISOString()
    }, null, 2));

    return;
  }

  // 404
  res.writeHead(404, { "Content-Type": "text/plain" });
  res.end("Not Found");
});

// ================= START =================
const PORT = process.env.PORT || 3000;

server.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});